[package]
name = "oxish"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.95"
aws-lc-rs = { version = "1.12", features = ["prebuilt-nasm"] }
bitflags = "2"
clap = { version = "4.5.58", features = ["derive"] }
listenfd = "1.0.2"
thiserror = "2.0.9"
tokio = { version = "1.42", features = ["io-util", "macros", "net", "process", "rt-multi-thread", "time"] }
tokio-stream = "0.1.18"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[target.'cfg(unix)'.dependencies]
rustix = { version = "1", features = ["termios", "pty", "process", "fs", "stdio"] }

[lints]
workspace = true
